### ISSUE TITLE
The application is crashing when the user tries to download an update on Android 6.X

### ISSUE THREAD

**Issue by SandroMachado** [AndroidVTS/android-vts#126]
The issue is related with `Android Runtime Permission` request. On Android 6.0 we need to ask for storage permission before downloading the update.

**Comment by m00head** [comment]
Created pull request #130

**Comment by m00head** [comment]
@SandroMachado Please will you review my fix?

**Comment by SandroMachado** [comment]
Sure 👍

**Comment by m00head** [comment]
@SandroMachado Pull request #130 has now been merged, so this issue can be closed.

**Comment by SandroMachado** [comment]
Closed by #130. @m00head thanks 👍
