### ISSUE TITLE
Build Error: `local.properties` Not Found

### ISSUE THREAD

**Issue by seamlik** [AndroidVTS/android-vts#144]
In a freshly cloned repository, `./gradlew assemble` throws an error complaining that `local.properties` was not found.

This is because [the build script](https://github.com/AndroidVTS/android-vts/blob/v.13/app/build.gradle#L55) explicitly relies on this file. However, `local.properties` is usually ignored by every Android projects (including this one), therefore it might not be a good practice.

**Comment by m00head** [comment]
Quote:
```
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
```

**Comment by seamlik** [comment]
I understand that this file should not be checked into the repository, that's why it is not a good practice to explicitly rely on this file. Otherwise the project might be unfriendly to any continuous integration servers. The build script should find a way to go on without the presence of `local.properties`.

**Comment by m00head** [comment]
Created pull request https://github.com/AndroidVTS/android-vts/pull/145 to resolve this issue

**Comment by Fuzion24** [comment]
Merged

**Comment by m00head** [comment]
This issue can now be closed
